---
title: "Soil carbon Analysis"
author: "Jay"
date: "04/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Import Packages -----------------------------------------------------------
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggpubr)
library(lme4)
library(lmerTest)
library(ggsignif)
library(ggsci)
library(scales)
library(vegan)
library(patchwork)
library(ggtext)


```

# Biomass Analysis --------------------------------------------------------
```{r fig.height=4, fig.width=8}
df_biomass <- read.csv("data/rf_biomass.csv" ) %>% 
  janitor::clean_names() %>% 
  drop_na()


mod_biomass <- lmer(sqrt(biomass) ~ plant_community + (1|size_of_patch) , data = df_biomass)
anova(mod_biomass)
lattice::qqmath(mod_biomass)
shapiro.test(resid(mod_biomass))


df_biomass %>% group_by(plant_community) %>% summarise(mean(biomass))

my_comparisions <- list(c("Knapweed","Natural"))

biomass <- ggplot(df_biomass, aes(x = plant_community,y = sqrt(biomass), fill = plant_community )) +
  geom_violin(width= 0.5, alpha = 0.6,show.legend = F) +
  geom_boxplot(width = 0.25) +
  stat_compare_means(comparisons = my_comparisions,
                     method =  "t.test",
                     label = "p.signif",
                     size = 6,
                     label.y = 1.25) +
  ylim(c(0,1.4))+
  theme_bw()+
  theme(panel.grid = element_blank(),
        legend.position = c(.999, .999),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(3, 3, 3, 3),
        legend.box.background = element_rect(color="black"),
        axis.text.x =  element_blank(),
        axis.ticks.x = element_blank()
        )+
  ggeasy::easy_all_text_colour(colour = "black") +
  ggeasy::easy_all_text_size(size =14) +
  scale_fill_jama(name = "Knapweed", labels = c("Invaded", "Uninvaded")) +
  labs(x = NULL,
       y = expression(sqrt(Biomass ~(g))))
biomass

ggsave(biomass, filename = "biomass.jpg",path = "./plot", width = 6, height = 4, units = "in",dpi = 800)
```


# Carbon model ------------------------------------------------


```{r, fig.height= 4, fig.width=8}
df_nut <- read.csv("data/soil_cn.csv") %>% 
  janitor::clean_names() %>% 
  mutate(cn = c_result/n_result)


# carbon model ------------------------------------------------------------

mod_carbon <- lmer(sqrt(c_result) ~ plant_community + (1|patch_size)  , data = df_nut)
lattice::qqmath(mod_carbon)
shapiro.test(resid(mod_carbon))
anova(mod_carbon)

df_nut %>% group_by(plant_community) %>% summarise(mean(c_result))
# Plot carbon data --------------------------------------------------------

my_comparisions <- list(c("knapweed","natural"))

plt_carbon <- ggplot(df_nut, aes(x = plant_community,y = sqrt(c_result), fill = plant_community )) +
  geom_violin(width= 0.5, alpha = 0.6, show.legend = F) +
  geom_boxplot(width = 0.25) +
  stat_compare_means(comparisons = my_comparisions,
                     method = "t.test",
                     label = "p.signif",
                     size = 6,
                     label.y = 3.5) +
   theme_bw()+
  theme(panel.grid = element_blank(),
        legend.position =c(.999, .999),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(3, 3, 3, 3),
        legend.box.background = element_rect(color="black"),
        axis.text.x =  element_blank(),
        axis.ticks.x = element_blank()
  )+
  ggeasy::easy_all_text_colour(colour = "black") +
  ggeasy::easy_all_text_size(size =14)  +
  labs(x = NULL,
       y = expression(sqrt(Carbon ~("%"))))  +
  scale_fill_jama(name = "Knapweed", labels = c("Invaded", "Uninvaded")) +
  ylim(c(1.5, 3.65))
plt_carbon

ggsave(plt_carbon, filename = "plt_carbon.jpg",path = "./plot", width = 6, height = 4, units = "in",dpi = 800)
```

# Nitrogen model ----------------------------------------------------------


```{r, fig.height= 4, fig.width=8}
mod_nitrogen <- lmer(sqrt(n_result) ~ plant_community + (1|patch_size)   , data = df_nut)
lattice::qqmath(mod_nitrogen)
shapiro.test(resid(mod_nitrogen))
anova(mod_nitrogen)


df_nut %>% group_by(plant_community) %>% summarise(mean(n_result))

# Plot nitrogen -----------------------------------------------------------

my_comparisions <- list(c("knapweed","natural"))

plt_nitro <- ggplot(df_nut, aes(x = plant_community,y = sqrt(n_result), fill = plant_community )) +
  geom_violin(width= 0.5, alpha = 0.6, show.legend = F) +
  geom_boxplot(width = 0.25) +
  stat_compare_means(comparisons = my_comparisions,
                     method = "t.test",
                     label = "p.signif",
                     size = 6,
                     label.y = 1.15) +
  ylim(c(0.4,1.25))+
  theme_bw()+
  theme(panel.grid = element_blank(),
        legend.position = c(.999, .999),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(3, 3, 3, 3),
        legend.box.background = element_rect(color="black"),
        axis.text.x =  element_blank(),
        axis.ticks.x = element_blank()
  )+
  ggeasy::easy_all_text_colour(colour = "black") +
  ggeasy::easy_all_text_size(size =14)  +
  labs(x = NULL,
       y = expression(sqrt(Nitrogen ~("%"))))  +
  scale_fill_jama(name = "Knapweed", labels = c("Invaded", "Uninvaded")) 
plt_nitro

ggsave(plt_nitro, filename = "plt_nitro.jpg",path = "./plot", width = 6, height = 4, units = "in",dpi = 800)
```

# C/N ratio ---------------------------------------------------------------


```{r, fig.height= 4, fig.width=8}

mod_cn <- lmer(cn ~ plant_community + (1|patch_size), data = df_nut)
lattice::qqmath(mod_cn)
shapiro.test(resid(mod_cn))
anova(mod_cn)



# plot CN -----------------------------------------------------------------

my_comparisions <- list(c("knapweed","natural"))

plt_CN <- ggplot(df_nut, aes(x = plant_community,y = cn, fill = plant_community ), show.legend = TRUE) +
  geom_violin(width= 0.5, alpha = 0.6, show.legend = F) +
  geom_boxplot(width = 0.25, show.legend = T) +
  stat_compare_means(comparisons = my_comparisions,
                     method = "t.test",
                     label = "p.signif",
                     size = 6,
                     label.y = 12.5) +
  ylim(c(9,13))+
  theme_bw()+
  theme(panel.grid = element_blank(),
        legend.position = c(.999, .999),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(3, 3, 3, 3),
        legend.box.background = element_rect(color="black"),
        axis.text.x =  element_blank(),
        axis.ticks.x = element_blank()
  )+
  ggeasy::easy_all_text_colour(colour = "black") +
  ggeasy::easy_all_text_size(size =14)  +
  labs(x = NULL,
       y = "Carbon / Nitrogen ")  +
  scale_fill_jama(name = "Knapweed", labels = c("Invaded", "Uninvaded"))
plt_CN

ggsave(plt_CN, filename = "plt_CN.jpg", path = "./plot", width = 6, height = 4, units = "in",dpi = 800)

```
# Combining carbon, nitrogen, CN ratio and biomass plot --------------


```{r, fig.height= 6, fig.width=8}
comb_plot <- (biomass + plt_carbon) / (plt_nitro + plt_CN  ) +
  plot_annotation(tag_levels = 'A', tag_prefix = "2") +
  plot_layout(guides = "collect") & theme(legend.position = 'bottom')

comb_plot_new <- comb_plot & theme(axis.title.y =  element_text(size = 24),
  legend.text =  element_text(size = 20),
  legend.title = element_text(size = 20))

comb_plot_new

ggsave (comb_plot_new, filename = "comb_plot.jpg", path = "./plot", width = 12, height = 10, units = "in", dpi = 900)
```



# Nutrient composition ------------------------------------------------

```{r, fig.height= 4, fig.width=8}
rf_biom <- read.csv("data/rf_biomass.csv") %>% 
  janitor::clean_names() %>% 
  mutate(id = str_remove(plant_id, "^[1-9]+-*")) %>% 
  drop_na() %>% 
  group_by(plant_community, id) %>% 
  summarise(bm = mean(biomass), .groups = "drop")%>% 
  mutate(id = str_remove(id, "-")) %>% 
  arrange(id)

cn_df <- read.csv("data/soil_cn.csv") %>% 
  janitor::clean_names() %>% 
  arrange(id) %>% 
  mutate(id = str_trim(id))

ele_df <- read.csv( "data/elements.csv" ) %>% 
  janitor::clean_names() %>% 
  arrange(code) 
 
df_ele <- ele_df %>% 
  select(-c(code, patch_size, plant_community, sample))

meta_ele <- ele_df %>% 
   rename(id = code) %>% 
  left_join(., rf_biom, by = "id") %>% 
  left_join(., cn_df, by = "id") %>% 
  rename(treatment = plant_community.x)

norm_ele <- vegan::decostand(df_ele, method = "normalize", MARGIN = 1)

pc <- prcomp(norm_ele)
summary(pc)$importance[,1:2]


PC1 <- pc$x[,1]
PC2 <- pc$x[,2]
plt_df <- data.frame(PC1, PC2,
                     meta_ele)

dist_eucc <- vegdist(norm_ele, method = "euclidean")

set.seed(11111)
adonis2(dist_eucc ~ plt_df$treatment)

nutrient_dis <- ggplot(plt_df, aes(PC1, PC2, fill = treatment))+
  stat_ellipse(geom = "polygon", level = 0.95, alpha = 0.3, show.legend = F) +
  geom_point(pch= 21, size = 5) +
  scale_fill_jama(name ="Knapweed",
                  label = c("Invaded", "Uninvaded")) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        legend.position = c(0.173, 0.999),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6),
        legend.box.background = element_rect(color="black")) +
  labs(x = "Axis 1 (Variance 51.29 %)",
       y = "Axis 2 (Variance 35.87 %)")  +
  annotate("text", label = "Pseudo F = 4.84; p = 0.006", x = 0.1, y = -0.12, size = 5 ) +
  ggeasy::easy_all_text_colour(colour = "black") +
  ggeasy::easy_all_text_size(size =14)
nutrient_dis
  ggsave(nutrient_dis, filename = "nutrient_dis.jpg",path = "./plot", width = 8, height = 6, units = "in",dpi = 800)





```

# Plotting all nutrients --------------------------------------------------


```{r fig.height= 10, fig.width=16}
ele_df <- read.csv( "data/elements.csv" ) %>% 
  janitor::clean_names(case = "upper_camel") %>% 
  select(-c(Sample, Code, PatchSize))



df_all_element <- ele_df%>% 
  pivot_longer(-PlantCommunity)

my_comparisions <- list(c("knapweed","natural"))


all_nut <- ggplot(df_all_element, aes(x = PlantCommunity,y = value, fill = PlantCommunity ), show.legend = TRUE) +
  geom_violin(width= 0.6, alpha = 0.6, show.legend = F) +
  geom_boxplot(width = 0.2) +
  stat_compare_means(comparisons = my_comparisions,
                     method = "t.test",
                     label = "p.signif",
                     vjust = 0.12,
                    size = 2.8,
                    geom = "text",
                    face = "bold") +
  theme_bw()+
  theme(panel.grid = element_blank(),
        axis.text.x =  element_blank(),
        axis.text.y =  element_text(size = 8),
        axis.ticks.x = element_blank(),
        axis.title.y = element_text(size = 16, face = "bold"),
        legend.position = "bottom",
        strip.background = element_rect(fill="darkgray", size=0.4),
        strip.text.x = element_text(size = 10, face = "bold"),
  legend.text = element_text(size = 16, face = "bold"),
  legend.title = element_text(size = 16, face = "bold"))+
  ggeasy::easy_all_text_colour(colour = "black") +
   labs(x = NULL,
       y = "Concentration (ppm)")  +
  scale_fill_jama(name = "Knapweed", labels = c("Invaded", "Uninvaded")) +
  facet_wrap(. ~ name, ncol = 4,  scales = "free_y") +
  scale_y_continuous(labels = label_scientific(digits = 1)) 
all_nut

ggsave(all_nut, filename = "all_nut.jpg",path = "./plot", width = 16, height = 10, units = "in",dpi = 800)
```




# Regression analysis-------------------------------------------------

```{r, message=FALSE, warning=FALSE, fig.height= 4, fig.width=12}

mod_c <- lm(c_result ~ PC1, data = plt_df)
summary(mod_c)

mod_n <- lm(n_result ~ PC1, data = plt_df)
summary(mod_n)

mod_bm <- lm(bm ~ PC1, data = plt_df)
summary(mod_bm)


p1 <- ggplot(plt_df, aes(x= PC1, y = c_result)) +
  geom_point(pch = 21, fill = "royalblue4", size = 4, alpha = 0.5) +
  geom_smooth(method = "lm", se = T, color = "black",  lwd = 1, linetype = 5) +
  theme_classic() +
  labs(y = "Carbon %",
       x = "PC axis 1") +
  annotate(geom = "text",
          y= 12, 
          x= 0,
          label = expression(paste(R["adj"]^2 ~"="~"0.32"~";" ~ "p <0.001")), size = 5)+
  ggeasy::easy_all_text_size(size = 14) +
  ggeasy::easy_all_text_color("black") +
  ylim(c(0,13))

p2 <- ggplot(plt_df, aes(x= PC1, y = n_result)) +
  geom_point(pch = 21, fill = "royalblue4", size = 4, alpha = 0.5) +
  geom_smooth(method = "lm", se = T, color = "black", lwd = 1, linetype = 5) +
  theme_classic() +
  labs(y = "Nitrogen %",
       x = "PC axis 1") +
  annotate(geom = "text",
          y= 1.2, 
          x= 0,
          label = expression(paste(R["adj"]^2 ~"="~"0.32"~";" ~ "p <0.001")), size = 5)+
  ggeasy::easy_all_text_size(size = 14)+
  ggeasy::easy_all_text_color("black")+
  ylim(c(0,1.3))

p3 <- ggplot(plt_df, aes(x= PC1, y = bm)) +
  geom_point(pch = 21, fill = "royalblue4", size = 4, alpha = 0.5) +
  geom_smooth(method = "lm", se = T, color = "black", lwd = 1, linetype = 5) +
  theme_classic() +
  labs(y = "Biomass (g)",
       x = "PC axis 1") +
  annotate(geom = "text",
          y= 0.8, 
          x= 0,
          label = expression(paste(R["adj"]^2~"="~"0.11"~";" ~ "p <0.005")), size = 5)+
  ggeasy::easy_all_text_size(size = 14)+
  ggeasy::easy_all_text_color("black")+
  ylim(c(0,0.85))
  
plt <- p1 + p2 + p3 + plot_annotation(tag_levels = 'A', tag_prefix = "4") & theme(axis.title = element_text(size = 20) )

plt

ggsave(plt, filename = "reg_plt.jpg",path = "./plot", width = 10, height = 3.25, units = "in", dpi = 1000)

```

